name: AiNpc
version: '1.0-SNAPSHOT'
main: rexfracht868454.ainpc.Main
api-version: 1.19
depend:
  - Citizens
commands:
  summonnpc:
    description: summon a npc
    usage: "/summonnpc <type> <name> <role>"